config/routes.rb
Rails.application.routes.draw do
  if ActiveStorage.respond_to?(:resolve_model_to_route)
    resolve("Spina::Parts::Image") { |image, options| route_for(ActiveStorage.resolve_model_to_route, image, options) }
    resolve("Spina::Parts::ImageVariant") { |image, options| route_for(ActiveStorage.resolve_model_to_route, image, options) }
    resolve("Spina::Parts::Attachment") { |attachment, options| route_for(ActiveStorage.resolve_model_to_route, attachment, options) }
  else
    resolve("Spina::Parts::Image") { |image, options| route_for(:rails_blob, image, options) }
    resolve("Spina::Parts::ImageVariant") { |image, options| route_for(:rails_representation, image, options) }
    resolve("Spina::Parts::Attachment") { |attachment, options| route_for(:rails_blob, attachment, options) }
  end
end

Spina::Engine.routes.draw do
  # API
  namespace :api, path: Spina.config.api_path do
    resources :pages, only: [:index, :show]
    resources :navigations, only: [:index, :show]
    resources :resources, only: [:index, :show] do
      resources :pages, only: [:index, :show]
    end
    resources :images, only: [:show]
  end

  # Backend
  namespace :admin, path: Spina.config.backend_path do
    root to: "pages#index"

    resource :account
    resource :theme, controller: :theme

    get "/settings/:plugin", to: "settings#edit", as: :edit_settings
    patch "/settings/:plugin", to: "settings#update", as: :settings

    resources :users

    # Sessions
    resources :sessions
    get "login" => "sessions#new"
    get "logout" => "sessions#destroy"

    # Passwords
    resources :password_resets

    resources :pages do
      member do
        get :edit_content
        get :edit_template
        get :children
        post :sort_one
      end

      collection do
        post :sort
      end

      resource :move, controller: "move_pages"
    end
    resources :page_select_options, only: [:show, :index] do
      post :search, on: :collection
    end
    resources :resource_select_options, only: [:show, :index] do
      post :search, on: :collection
    end
    resources :page_translations, only: [:destroy]
    resources :parent_pages
    resource :layout, controller: :layout, only: [:edit, :update]

    resources :resources, only: [:show, :edit, :update]

    resources :navigations, only: [:index, :edit, :update] do
      post :sort, on: :member
      resources :navigation_items
    end

    resources :attachments do
      post :inline_upload, on: :collection
    end
    resources :rename_files

    resources :media_folders do
      resources :images
    end

    resources :images

    resource :media_picker, controller: "media_picker", only: [:show]

    resources :embeds, only: [:new, :create]
  end

  # Sitemap
  resource :sitemap

  unless Spina.config.disable_frontend_routes
    # Frontend
    root to: "pages#homepage"

    # Pages
    get "/:locale/*id" => "pages#show", :constraints => {locale: /#{Spina.config.locales.join('|')}/}
    get "/:locale/" => "pages#homepage", :constraints => {locale: /#{Spina.config.locales.join('|')}/}
    get "/*id" => "pages#show", :as => "page", :controller => "pages", :constraints => ->(request) {
      request.path.exclude?(ActiveStorage.routes_prefix) &&
        !(Rails.env.development? && request.path.starts_with?("/rails/"))
    }
  end
end

app/models/spina/parts/attachment.rb
module Spina
  module Parts
    class Attachment < Base
      attr_json :attachment_id, :integer, default: nil
      attr_json :signed_blob_id, :string, default: nil
      attr_json :filename, :string, default: ""

      def content
        self
      end

      def present?
        signed_blob_id.present?
      end

      # Rails 7.1 started using 'expires_at', so we 
      # include both expires_in and expires_at for backwards
      # compatibility
      def signed_id(expires_at: nil, expires_in: nil)
        signed_blob_id
      end
    end
  end
end

app/models/spina/parts/base.rb
module Spina
  module Parts
    class Base
      include AttrJson::Model

      attr_json_config(unknown_key: :strip)

      attr_json :name, :string

      attr_accessor :title, :hint, :item_name

      def label
        content&.to_s
      end

      def content
      end
    end
  end
end

app/models/spina/parts/datetime.rb
module Spina
  module Parts
    class Datetime < Base
      attr_json :content, :datetime, default: ""

      attr_accessor :options
    end
  end
end

app/models/spina/parts/image.rb
module Spina
  module Parts
    class Image < Base
      attr_json :image_id, :integer, default: nil
      attr_json :signed_blob_id, :string, default: nil
      attr_json :alt, :string, default: ""
      attr_json :filename, :string, default: ""

      attr_accessor :options

      def to_s
        alt.presence || filename.presence || Spina::Image.model_name.human
      end

      def content
        self
      end

      def svg?
        filename.end_with?(".svg")
      end

      def spina_image
        Spina::Image.find_by(id: image_id)
      end

      def present?
        signed_blob_id.present?
      end

      # Rails 7.1 started using 'expires_at', so we 
      # include both expires_in and expires_at for backwards
      # compatibility
      def signed_id(expires_at: nil, expires_in: nil)
        signed_blob_id
      end

      def variant(options)
        Spina::Parts::ImageVariant.new(self, options)
      end
    end
  end
end

app/models/spina/parts/image_collection.rb
module Spina
  module Parts
    class ImageCollection < Base
      include AttrJson::NestedAttributes

      attr_json :images, Image.to_type, array: true
      attr_json_accepts_nested_attributes_for :images

      def to_s
        Spina::Parts::ImageCollection.model_name.human
      end

      def content
        (images || [])
      end

      def image_ids
        content.map(&:image_id)
      end
    end
  end
end

app/models/spina/parts/image_variant.rb
module Spina
  module Parts
    class ImageVariant
      ImageVariation = Struct.new(:key)

      attr_reader :blob

      def initialize(image, options)
        @blob = image
        @options = options
      end

      def variation
        ImageVariation.new(ActiveStorage::Variation.encode(@options))
      end
    end
  end
end

app/models/spina/parts/line.rb
module Spina
  module Parts
    class Line < Base
      attr_json :content, :string, default: ""
    end
  end
end

app/models/spina/parts/multi_line.rb
module Spina
  module Parts
    class MultiLine < Base
      attr_json :content, :string, default: ""
    end
  end
end

app/models/spina/parts/option.rb
module Spina
  module Parts
    class Option < Base
      attr_json :value, :string, default: ""

      attr_accessor :options

      def content
        value
      end
    end
  end
end

app/models/spina/parts/page.rb
module Spina
  module Parts
    class Page < Base
      attr_json :page_id, :integer, default: nil

      def content
        Page.live.find_by(id: page_id)
      end
    end
  end
end

app/models/spina/parts/page_link.rb
module Spina
  module Parts
    class PageLink < Base
      attr_json :page_id, :integer, default: nil
      attr_json :text, :string, default: nil

      attr_accessor :options

      def content
        ::Spina::Page.live.find_by(id: page_id)
      end
    end
  end
end

app/models/spina/parts/repeater.rb
module Spina
  module Parts
    class Repeater < Base
      include AttrJson::NestedAttributes

      attr_json :content, RepeaterContent.to_type, array: true
      attr_json_accepts_nested_attributes_for :content
    end
  end
end

app/models/spina/parts/repeater_content.rb
module Spina
  module Parts
    class RepeaterContent < Base
      include Partable
      include AttrJson::NestedAttributes

      attr_json :parts, AttrJson::Type::SpinaPartsModel.new, array: true
      attr_json_accepts_nested_attributes_for :parts

      def find_part(name)
        (parts || []).find { |part| part.name.to_s == name.to_s }
      end
    end
  end
end

app/models/spina/parts/resource_link.rb
module Spina
  module Parts
    class ResourceLink < Base
      attr_json :resource_id, :integer, default: nil

      attr_accessor :options

      def content
        ::Spina::Resource.find_by(id: resource_id)
      end
    end
  end
end

app/models/spina/parts/text.rb
module Spina
  module Parts
    class Text < Base
      attr_json :content, :string, default: ""
    end
  end
end

app/views/spina/admin/parts/_image.html.haml
- image = Spina::Parts::Image.new(field)
- image.value = object.content[field]["value"]

.horizontal-form-group
  .horizontal-form-label
    = field
  .horizontal-form-content
    = f.fields_for field do |ff|
      = ff.hidden_field "partable_type", value: "Spina::Parts::Image"

      = link_to admin_media_picker_path(selected_ids: [object.content[field]["value"]["id"]], hidden_field_id: "#{field}_input"), remote: true, class: 'media_picker clearfix' do
        = ff.hidden_field "[value][id]", value: object.content[field]["value"]["id"], data: {hidden_field_id: "#{field}_input"}

        - image.image_urls.each do |image_url|
          = ff.text_field "[value][#{image_url}]", value: object.content[field]["value"][image_url], data: {hidden_field_url: image_url}, placeholder: image_url

        .placeholder
          %span.button.button-small.button-round
            %i.icon.icon-dots
            =t 'spina.images.choose_image'

          / - if image.content.attached?
          /   %br/

          / %span.button.button-small.button-round{data: {action: "click->image-form#remove", target: "image-form.button"}}
          /   %i.icon.icon-trash
          /   =t 'spina.images.remove_image'

        .image{data: {target: 'image-form.image'}}
          = image_tag image.thumbnail_url

app/views/spina/admin/parts/_line.html.haml
.horizontal-form-group
  .horizontal-form-label
    = field
  .horizontal-form-content
    = f.hidden_field "#{field}[partable_type]", value: "Spina::Parts::Line"
    = f.text_field "#{field}[value]", value: object.content[field]["value"]

app/views/spina/admin/parts/_structure.html.haml
.horizontal-form-group
  .horizontal-form-label
    = field
  .horizontal-form-content
    Structure form goes here

app/views/spina/admin/parts/_text.html.haml
.horizontal-form-group
  .horizontal-form-label
    = field
  .horizontal-form-content
    = f.fields_for field do |ff|
      = ff.hidden_field "partable_type", value: "Spina::Parts::Text"
      = ff.hidden_field "value", id: "#{field}_input", value: object.content[field]["value"]
      %trix-editor.text-input.trix-content{input: "#{field}_input"}